Fix 'Error: "." is not in the SourceMap.'
webpack/webpack-sources pull request #88
Opened 2020-09-23 13:50 UTC by MarcelloPerathoner

Fixes the error: UnhandledPromiseRejectionWarning: Error: "." is not in the SourceMap.

Without the true parameter the function throws but we don't catch. With the true parameter the function returns null, which we check.

2020-09-23 13:52 UTC, evilebottnawi requested changes
Please add tests

2020-09-23 19:17 UTC, dlong500 commented
I get that passing `true` as the second parameter prevents the error, but what is actually causing that function to be called with a period for the first parameter?  I'm a bit worried that always passing `true` will just obscure a real problem with source map generation (such that the build succeeds, but the source maps are invalid).  The error is reproducible, but only under certain configurations.  And what is the point of `sourceContentFor()` even having a `nullOnMissing` parameter if we always set it to `true`?

2020-09-23 19:32 UTC, MarcelloPerathoner commented
Using the same reasoning the parameter should be removed from version 1.4.3. and from the other similar function call too.

Adding the parameter makes version 1.4.3 and 2.0.0 behave in a consistent way.

My build process crashed after upgrading from webpack@5.0.0-beta-something to -rc0. Works again with that parameter set.

2020-09-23 19:46 UTC, dlong500 commented
I understand, but I am interested what is actually going on internally.  Based on the actual source-map code comments it looks like the primary reason for the `nullOnMissing` parameter is because it is used internally in a recursive way.  And just because the build succeeds doesn't mean the source maps are correct in this situation.  Maybe they are, just not sure.  I'm not enough of an expert with source maps to do a bunch of testing--just curious about how all this is playing out.

2020-09-23 20:02 UTC, MarcelloPerathoner commented
My build completes with webpack@5.0.0-beta.27 and crashes with webpack@5.0.0-beta.28. That is when terser was upgraded from 3 to 4.

2020-09-28 13:44 UTC, chaffeqa commented
FYI this fix works for us, I agree I'd love to know the underlying reason for allowing nulls, but my guess is its artifacts from removing typings or tree shaking along the way (optimizations from terser?)

2020-09-28 13:45 UTC, evilebottnawi commented
We will fix it in near future, don't worry

2021-08-02 09:53 UTC, sokra commented
fixed

2021-08-02 09:53 UTC, closed without merging